# pgdn-ws Configuration Example
# Save as pgdn_notify_config.yml in your project root

# Rate limiting configuration
rate_limits:
  # Slack notifications: 10 calls per minute
  slack:
    calls: 10
    period: 60
  
  # Email notifications: 50 calls per hour
  email:
    calls: 50
    period: 3600
  
  # Webhook notifications: 100 calls per hour
  webhook:
    calls: 100
    period: 3600
  
  # WebSocket notifications: 200 calls per hour
  websocket:
    calls: 200
    period: 3600

# Redis configuration for distributed rate limiting
# Set to true to use Redis-backed rate limiting (recommended for production)
use_redis_rate_limit: false

# Note: You can also configure rate limits via environment variables:
# PGDN_NOTIFY_RATE_LIMIT_ENABLED=true
# PGDN_NOTIFY_RATE_LIMIT_SLACK_CALLS=10
# PGDN_NOTIFY_RATE_LIMIT_SLACK_PERIOD=60
# PGDN_NOTIFY_USE_REDIS_RATE_LIMIT=true 